Ajout de quelque surchage utiles et changement de version en constante .
MoxieN/Bird pull request #1
Opened 2022-06-14 20:14 UTC by S0dlive

J'ai aussi corrigé la class Command .

2022-06-15 05:08 UTC, Kiirx requested changes
Command changes are to clarify, WriteLine(int number) needs to be changes

2022-06-15 05:08 UTC, Kiirx commented on Bird/Command.cs
> +    public abstract class Command
Why should it be abstract if we dont use it?

2022-06-15 05:08 UTC, Kiirx commented on Bird/Bird.cs
> +        public const string version = "v1.0.1"; // Il y a pas de ctor  donc . . .
Please set this comment in **ENGLISH**

2022-06-15 05:08 UTC, Kiirx commented on Bird/Bird.cs
> +        /// <param name="character">The char to output</param>
This parameter needs to be changed to number.

2022-06-15 05:08 UTC, Kiirx commented on Bird/Bird.cs
> +            Console.Write(number);
This isnt good, its a WriteLine method, and so, a \n is required.

2022-06-15 10:58 UTC, S0dlive commented on Bird/Command.cs
> +    public abstract class Command
simplement parce que je ne vois pas l'intérêt d'avoir une class instanciable quand derrière tu fais du polymorphisme (x

2022-06-15 12:04 UTC, Kiirx commented on Bird/Command.cs
> +    public abstract class Command
that's nonsense, I still dont see why you make it abstract

2022-06-15 12:47 UTC, S0dlive commented on Bird/Command.cs
> +    public abstract class Command
so you created a class that aims to do polymorphism and you make it instantiable? Also, your class doesn't have a ctor. . .

2022-06-26 12:45 UTC, Kiirx commented
I can merge this if you fix your code.

2022-10-22 19:06 UTC, closed without merging